### ISSUE TITLE
dynamicsFlexPlugin.js 

### ISSUE THREAD

**Issue by devconnectcrm** [kris-payne/Twilio-Flex-with-Dynamics365#2]
Am not able to compile your code for some reason, could you please help me.

Error: 

./src/TwilioDynamicsPlugin.js
  Line 4:1:  Parsing error: Unexpected character '​'

  2 | const loadjs = require ("loadjs")
  3 | const PLUGIN_NAME = 'TwilioDynamicsPlugin';
> 4 | ​
    | ^
  5 | ​
  6 | export default class TwilioDynamicsPlugin extends FlexPlugin {
  7 |   constructor() {

Also, am seeing this error loadjs is not defined.

**Comment by kris-payne** [comment]
Have you added the loadJS (node module) dependency in your package.json file https://www.npmjs.com/package/loadjs
```
`  "dependencies": {
    "@craco/craco": "^5.0.2",
    "babel-polyfill": "^6.26.0",
    "core-js": "^2.6.5",
    "craco-config-flex-plugin": "^2",
    "enzyme": "^3.10.0",
    "enzyme-adapter-react-16": "^1.14.0",
    "flex-plugin": "^2",
    "loadjs": "^4.0.1",
    "react": "16.5.2",
    "react-dom": "16.5.2",
    "react-scripts": "^3.0.0",
    "react-test-renderer": "^16.8.6"
  },`
```
